# Generated by Django 4.1.7 on 2023-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='goku.jpg', null=True, upload_to=''),
        ),
    ]
