# Generated by Django 4.1.7 on 2023-07-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
